# Site settings
title: Herpinator
email: robbob77herps@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Herpetology photography with a focus on snakes and some stars.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
instagram_username: herpinator77
github_username: robbob77

# Build settings
markdown: kramdown
permalink: pretty
